id = "zed-ctrmml"
name = "ctrmml"
version = "0.1.1"
schema_version = 1
authors = ["ulalume"]
description = "ctrmml language support for Zed"
repository = "https://github.com/ulalume/zed-ctrmml"

[grammars.ctrmml]
repository = "https://github.com/ulalume/tree-sitter-ctrmml"
rev = "335ed0bdfc6169219740fc4ce4d3f0a8e33d5f6a"

[language_servers.ctrmml]
name = "ctrmml LSP"
languages = ["ctrmml"]
