id = "zed-ctrmml"
name = "ctrmml"
version = "0.0.12"
schema_version = 1
authors = ["ulalume"]
description = "ctrmml language support for Zed"
repository = "https://github.com/ulalume/zed-ctrmml"

[grammars.ctrmml]
repository = "https://github.com/ulalume/tree-sitter-ctrmml"
rev = "d9f898f5f2ccdbbde53cc73af670dee05e3f26d1"

[language_servers.ctrmml]
name = "ctrmml LSP"
languages = ["ctrmml"]
