id = "zed-ctrmml"
name = "ctrmml"
version = "0.1.0"
schema_version = 1
authors = ["ulalume"]
description = "ctrmml language support for Zed"
repository = "https://github.com/ulalume/zed-ctrmml"

[grammars.ctrmml]
repository = "https://github.com/ulalume/tree-sitter-ctrmml"
rev = "eea5049716e79444e46423410ea2c88f438dcffe"

[language_servers.ctrmml]
name = "ctrmml LSP"
languages = ["ctrmml"]
